name: Deploy to Cloud Run

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
      REGION: europe-west3
      SERVICE: ${{ secrets.GCP_PROJECT_ID }}-streak-server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        uses: google-github-actions/deploy-cloudrun@v0.6.0
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE_NAME }}
          region: ${{ env.REGION }}
          env_vars: ${{ format('DB_CONNECTION_STRING={0},\
            CLIENT_ORIGIN_URL={1},\
            AUTH0_AUDIENCE={2},\
            AUTH0_DOMAIN={3}',
            secrets.DB_CONNECTION_STRING,
            secrets.CLIENT_ORIGIN_URL,
            secrets.AUTH0_AUDIENCE,
            secrets.AUTH0_DOMAIN
            )}}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
